### ISSUE TITLE
PropertyFiltering doesn't work when using Jackson 2.10

### ISSUE THREAD

**Issue by kvirkki** [HubSpot/jackson-jaxrs-propertyfiltering#19]
Works still with 0.8.3 version, but the performance improvements in 0.8.4 seem to have broken it.

I think that PropertyFilteringJsonGenerator needs some fix as it's extending JsonGeneratorDelegate and that one has changed in Jackson 2.10.

Here's the stack trace I'm seeing thrown:

```
com.fasterxml.jackson.core.JsonGenerationException: Can not start an array, expecting field name (context: Object)
	at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:2080)
	at com.fasterxml.jackson.core.json.JsonGeneratorImpl._reportCantWriteValueExpectName(JsonGeneratorImpl.java:248)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._verifyValueWrite(UTF8JsonGenerator.java:1132)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeStartArray(UTF8JsonGenerator.java:331)
	at com.fasterxml.jackson.core.JsonGenerator.writeStartArray(JsonGenerator.java:770)
	at com.fasterxml.jackson.core.util.JsonGeneratorDelegate.writeStartArray(JsonGeneratorDelegate.java:206)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:78)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1433)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:921)
	at com.hubspot.jackson.jaxrs.PropertyFilteringMessageBodyWriter.writeValue(PropertyFilteringMessageBodyWriter.java:128)
	at com.hubspot.jackson.jaxrs.PropertyFilteringMessageBodyWriter.writeTo(PropertyFilteringMessageBodyWriter.java:72)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.writeMessageBody(JAXRSUtils.java:1472)
```

**Comment by jhaber** [comment]
Sorry about that, I can take a look shortly. I also updated the Travis config so that we test against Jackson 2.9.10 and 2.10 (in addition to 2.9.9):
https://github.com/HubSpot/jackson-jaxrs-propertyfiltering/blob/54dee3d59e16d28f13973090f961739f0ac881e6/.travis.yml#L6-L9

**Comment by jhaber** [comment]
Nevermind, those env vars worked locally but don't seem to work in Travis 🤔

**Comment by jhaber** [comment]
Travis setup seems to be working now with:
https://github.com/HubSpot/jackson-jaxrs-propertyfiltering/blob/450ebc9ab11c91694b944e9e6ebcf333f2e8f7dd/.travis.yml#L6-L11

**Comment by jhaber** [comment]
Should be fixed by #20, I can cut a new release shortly. This should also be less fragile once https://github.com/FasterXML/jackson-core/pull/573 lands because this code will live in jackson-core and stay in sync

**Comment by kvirkki** [comment]
Awesome! :) Thank you so much!

**Comment by jhaber** [comment]
No problem, sorry for the headache. 0.8.5 is released and should show up in Maven Central shortly. I also added a warning to the 0.8.4 release notes
